### ISSUE TITLE
Add option to read pki from file

### ISSUE THREAD

**Issue by domdom82** [domdom82/go-ca#2]
Could be a yaml file like:

```
---
root:
  type: root
  name: "Company abc Root CA"
  dn: etc.
  start-date: ddmmyy-ssmmhh
  expiry-date: ddmmyy-ssmmhh
  chain:
    - intermediate-A:
      type: intermediate
      name: "Company abc Intermediate CA"
      (...)
      chain:
      - intermediate-B:
        (...)
        chain:
           - server-cert-one:
              type: server
              name: server-one.abc.com
              (...)
          - client-cert-one:
             type: client
             name: client-one@abc.com
             (...)
```
